/* PRODUCT SEQ & TRIGGER */

CREATE SEQUENCE PRODUCT_NO_SEQ
	START WITH 1
	INCREMENT BY 1;

DROP SEQUENCE product_no_seq;

CREATE OR REPLACE TRIGGER TRI_PRODUCT_NO_SEQ
BEFORE INSERT ON PRODUCT
FOR EACH ROW 
BEGIN
	IF Inserting AND :NEW.PRODUCT_NO IS NULL THEN
		SELECT PRODUCT_NO_SEQ.NEXTVAL INTO :NEW.PRODUCT_NO FROM DUAL;
END IF;
END;


/* CART SEQ & TRIGGER */

CREATE SEQUENCE CART_NO_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRI_CART_NO_SEQ
BEFORE INSERT ON CART
FOR EACH ROW 
BEGIN
	IF Inserting AND :NEW.CART_NO IS NULL THEN
		SELECT CART_NO_SEQ.NEXTVAL INTO :NEW.CART_NO FROM DUAL;
END IF;
END;


/* ORDER SEQ * TRIGGER */

CREATE SEQUENCE ORDERS_NO_SEQ
	START WITH 1
	INCREMENT BY 1;

DROP SEQUENCE orders_no_seq;

CREATE OR REPLACE TRIGGER TRI_ORDERS_NO_SEQ
BEFORE INSERT ON ORDERS
FOR EACH ROW 
BEGIN
	IF Inserting AND :NEW.ORDERS_NO IS NULL THEN
		SELECT ORDERS_NO_SEQ.NEXTVAL INTO :NEW.ORDERS_NO FROM DUAL;
END IF;
END;


/* ORDER DETAIL SEQ * TRIGGER */

CREATE SEQUENCE ORDER_DETAIL_NO_SEQ
	START WITH 1
	INCREMENT BY 1;

DROP SEQUENCE order_detail_no_seq;

CREATE OR REPLACE TRIGGER TRI_ORDER_DETAIL_NO_SEQ
BEFORE INSERT ON ORDER_DETAIL
FOR EACH ROW 
BEGIN
	IF Inserting AND :NEW.ORDER_DETAIL_NO IS NULL THEN
		SELECT ORDER_DETAIL_NO_SEQ.NEXTVAL INTO :NEW.ORDER_DETAIL_NO FROM DUAL;
END IF;
END;


/* QNA SEQ & TRIGGER */
CREATE SEQUENCE QNA_NO_SEQ
	START WITH 1
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER QNA_NO_SEQ
BEFORE INSERT ON QNA
FOR EACH ROW 
BEGIN
	IF Inserting AND :NEW.QNA_NO IS NULL THEN
		SELECT QNA_NO_SEQ.NEXTVAL INTO :NEW.QNA_NO FROM DUAL;
END IF;
END;