/* 신상품 4개 */

CREATE OR REPLACE VIEW NEW_PRO_VIEW
AS
SELECT PRODUCT_NO, PRODUCT_NAME, SALE, PRODUCT_IMAGE
FROM (
	SELECT ROWNUM, PRODUCT_NO, PRODUCT_NAME, SALE, PRODUCT_IMAGE
	FROM PRODUCT
	WHERE DEL_YN = 'n'
	ORDER BY REG_DATE DESC
)
WHERE ROWNUM <= 4;

SELECT PRODUCT_NO, PRODUCT_NAME, SALE, PRODUCT_IMAGE FROM new_pro_view;

SELECT PRODUCT_NO, PRODUCT_NAME, PRODUCT_KIND, PRICE, SALE, MARGIN, PRODUCT_CONTENT, PRODUCT_IMAGE, DEL_YN, BEST_YN, REG_DATE FROM product;

/* 베스트 상품 */