INSERT INTO BOARD(NAME, EMAIL, PASS, TITLE, CONTENT) VALUES (?, ?, ?, ?, ?);
UPDATE BOARD SET NAME = '성윤정', EMAIL = 'pinksung@nate.com', PASS = '1234', TITLE = '첫방문', CONTENT = '반갑습니다' WHERE NUM = 1;
DELETE BOARD WHERE NUM = ?;

SELECT * FROM board;

SELECT * FROM MEMBER;

DELETE MEMBER WHERE member_id = 'banana';

SELECT * FROM PRODUCT;
SELECT * FROM cart;
SELECT * FROM ORDER_DETAIL;
SELECT * FROM ORDERS;
SELECT * FROM MEMBER;
SELECT * FROM WORKER;
SELECT * FROM ORDER_VIEW;
SELECT * FROM order_view WHERE member_id = 'one' AND RESULT LIKE '%1%' and orders_no = 26;
SELECT * FROM qna;

